Story/WORK-53 - Define the Operator interface
inspr/primal pull request #3
Opened 2021-07-28 10:51 UTC by aluchianic

- [x] defined Operators interface
- [x] defined Platform interface
- [x] updated main.go
- [x] updated Web platform according to new design

2021-07-28 13:05 UTC, franciscobonand requested changes

2021-07-28 13:05 UTC, franciscobonand commented on pkg/platform/web.go
> +		// Watch: &esbuild.WatchMode{
Can probably remove this commented part

2021-07-28 13:05 UTC, franciscobonand commented on pkg/operator/logger.go
> +		ID:    "loggerTask",
Should probaly change this ID to be the same as the one used in the `MainOps` structure (in interface.go)

2021-07-28 13:05 UTC, franciscobonand commented on pkg/operator/html.go
> +		ID:    "htmlTask",
Same ID thing here

2021-07-28 13:05 UTC, franciscobonand commented on pkg/operator/disk.go
> +		ID:    "diskTask",
Same ID thing here

2021-07-28 13:05 UTC, franciscobonand commented on pkg/operator/disk.go
>  				// TODO: catch the error and return in an "errors" chan
Can this comment be removed?

2021-07-29 00:07 UTC, brenordr commented on cmd/primal/main.go
> +			Platform: "web",
@aluchianic @franciscobonand should we make it an enum?
so we refer it as `api.PlatformWeb` or something like it?
It can conflict if we are expecting to deserialize though

2021-07-29 11:23 UTC, franciscobonand commented on cmd/primal/main.go
> +			Platform: "web",
Sure, I think we can do something like:
```
type PlatformType string

const(
    PlatformWeb PlatformType = "web"
    PlatformElectron = "electron"
    PlatformNative = "native"
    ...
)
```

2021-08-02 11:41 UTC, franciscobonand approved these changes

2021-08-02 11:41 UTC, merged