Story WORK-70 | Implement hot reload on dev-server
inspr/primal pull request #8
Opened 2021-08-04 08:58 UTC by aluchianic

# Description

**Kind:**
Story

**Section:**
"platform/dev-server"
"template/index.txs"

**Summary:**
Added two ws handlers on dev-server 
1. `got-update` - send message to Client whenever bundler updated
2. `json` - to send data as JSON from Client to Server 

## Changelog

Server handlers
WS Client side initialization

## Pay attention to

> Important parts of the code that require special attention

2021-08-04 15:55 UTC, franciscobonand requested changes

2021-08-04 15:55 UTC, franciscobonand commented on pkg/platform/dev-server.go
> +			return
By using `defer` in line 107 it will be called **after**:
```go
case <-ctx.Done():
			c.Close(websocket.StatusNormalClosure, "")
			return
```
is this the desired behaviour?

2021-08-04 15:55 UTC, franciscobonand commented on template/index.tsx
> +    const conn = new WebSocket(`ws://${location.host}/ws`)
I believe @brenordr said something about hosting the websocket connection not in `/ws` but in some other path. Might want to check this with him

2021-08-05 06:57 UTC, aluchianic commented on pkg/platform/dev-server.go
> +			return
this part i got from [example](https://github.com/nhooyr/websocket/blob/8dee580a7f74cf1713400307b4eee514b927870f/examples/echo/server.go#L23) of websocket lib that we are using, so i think it's right behavior

2021-08-05 11:02 UTC, franciscobonand approved these changes

2021-08-05 11:03 UTC, merged