Bug WORK-73 | Empty index.html creation
inspr/primal pull request #9
Opened 2021-08-04 14:59 UTC by Rmgreco

Type: Bug Fix

Section: Operators, platform web, worflow

Summary:
-The bug where an empty index.html was created when there was no template to be rendered was fixed
-The tasks structure in workflow in now a map

Pay attention to:
The user needs to have a template folder in the root folder to be rendered.

2021-08-04 16:05 UTC, franciscobonand commented on pkg/operator/disk.go
> +				if _, err := os.Stat(path); os.IsNotExist(err) {
`erro` would be better called `err`. In line 30 you'd just need to change from `if _, err := ...` to `if _, err = ...`

2021-08-04 16:05 UTC, franciscobonand commented on pkg/operator/disk.go
> +				self.ErrChan <- erro
After this `else if` clause, it might be a good idea to add an `else` and do `panic(err)` inside this else (in this case, the error received is an unexpected error)

2021-08-04 16:05 UTC, franciscobonand commented on pkg/platform/web.go
> +	web.Platform.Workflow.Tasks = map[string]*workflow.Task{}
This map initialization should be done in the method `func NewWorkflow()` in `workflow.go`

2021-08-04 16:05 UTC, franciscobonand commented on pkg/workflow/workflow.go
> +	// w.Tasks = append(w.Tasks, &task)
Remove this comment

2021-08-04 16:10 UTC, franciscobonand requested changes
After resolving the changes I pointed out, it is a good idea to run all the unit tests to see if none of them broke. You can do so by running `go test ./...` from within the root

2021-08-05 13:28 UTC, aluchianic approved these changes

2021-08-05 13:28 UTC, aluchianic commented on pkg/workflow/workflow.go
> +	if len(t.Dependencies) == 0 {
if think it can be used just as 
```
if !len(t.Dependencies) {
...
```

2021-08-05 14:23 UTC, aluchianic approved these changes

2021-08-05 17:09 UTC, franciscobonand approved these changes

2021-08-05 17:14 UTC, merged